rule create_read_count_panel_of_normals:
    input:
        # Required inputs in either hdf5 or tsv format.
        # Inputs should be generated by running CollectReadCounts.
        count_file = '{sample}.counts.hdf5',
        # Optional inputs. Omit if unused.
        # GC-content annotated-intervals file from AnnotateIntervals.
        # If specified, explicit GC-bias correction will be performed on the panel samples,
        # and identically for subsequent case samples.
        annotated_intervals = 'annotated_intervals.tsv',
        # Panel-of-normals from `CreateReadCountPanelOfNormals`. It will be used to standardize
        # and denoise the input counts.
        count_panel_of_normals = 'panel_of_normals.pon.hdf5',
    output:
        # Required output PON file. MUST be hdf5 format.
        standardized_copy_ratios = '{sample}.standardized_copy_ratios.tsv',
        denoised_copy_ratios = '{sample}.denoised_copy_ratios.tsv',
    params:
        # Optional parameters. Omit if unused.
        extra = '',
    threads: 1
    wrapper:
        'http://dohlee-bio.info:9193/gatk/cnv/denoise-read-counts'
