# Define sample names which will be used to make panel of normals.
PON_SAMPLES = ['sample1', 'sample2']

rule create_read_count_panel_of_normals:
    input:
        # Required inputs in either hdf5 or tsv format.
        # Inputs should be generated by running CollectReadCounts.
        count_files = expand('result/{sample}/{sample}.counts.hdf5', sample=PON_SAMPLES)
        # Optional inputs. Omit if unused.
        # GC-content annotated-intervals file from AnnotateIntervals.
        # If specified, explicit GC-bias correction will be performed on the panel samples,
        # and identically for subsequent case samples.
        annotated_intervals = ''
    output:
        # Required output PON file. MUST be hdf5 format.
        'pon.hdf5'
    params:
        # Optional parameters. Omit if unused.
        extra = '',
    threads: 1
    log: 'logs/gatk/create-read-count-panel-of-normals/PON.log'
    wrapper:
        'http://dohlee-bio.info:9193/gatk/cnv/create-read-count-panel-of-normals'
